# Generated by Django 4.2.6 on 2023-12-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsApp', '0002_author_comment_post_postcategory_subscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='news_type',
        ),
    ]
